name: Run MATLAB Commands 
on: 
  workflow_dispatch:
    inputs:
      workspase:
        description: "put your scripts into workspase"
        default: "workspace1"
        required: true
      script_name:
        description: "matlab script name without .m"
        default: "Rayleigh_fading"
        required: true
      release_tag:
        description: "name of publish version"
        default: "Rayleigh_fading_v1"
        required: true
      assets_name:
        description: "name of assets publishing"
        default: "data.zip"
        required: true

jobs:
  my-job:
    name: Run MATLAB Commands
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
      - name: Run commands
        run: cd ${{ github.event.inputs.workspase }} && matlab -batch ${{ github.event.inputs.script_name }}
      - name: Zip the workspace
        run: zip -r data.zip ${{ github.event.inputs.workspase }}/ && ls -h
      - name: Upload data to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: data.zip
          asset_name: ${{ github.event.inputs.assets_name }}
          tag: ${{ github.event.inputs.release_tag }}
          overwrite: true
          body: "Release savefile of ${{ github.event.inputs.script_name }}"
